version: '3.1'

services:
  web:
    container_name: {{name}}-web
    image: wordpress:php7.3-apache
    command: bash -c "curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp && exec apache2-foreground"
    depends_on:
      - db
    ports:
      - 8000:80
    volumes:
      - ./web:/var/www/html/
    env_file:
      - ./.env
  db:
    container_name: {{name}}-db
    image: mariadb
    ports:
      - 13306:3306
    env_file:
      - ./.env
    volumes:
      - ./database:/database
